import os
from pathlib import Path
import torch
import numpy as np
from PIL import Image, ImageDraw
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoProcessor, Florence2ForConditionalGeneration
from atomic_kg_builder import VectorAtomicKnowledgeGraph

# ==========================================
# 1. CONFIGURATION & CONSTANTS
# ==========================================

# [PATH CHANGE] Resolve Project_Root (4 levels up from RM/Aditya/Graph_Approach/)
SCRIPT_DIR = Path(__file__).parent.parent.parent.parent

# [PATH CHANGE] Centralized input directory
INPUT_FOLDER = SCRIPT_DIR / "Input_Images"

# [PATH CHANGE] Team-specific output directory
TEAM_MEMBER = "Aditya"
MODULE_NAME = "Graph_Approach"
OUTPUT_BASE = SCRIPT_DIR / "Output_Images" / TEAM_MEMBER / MODULE_NAME
OUTPUT_BASE.mkdir(parents=True, exist_ok=True)

# [PATH CHANGE] Model cache directory
os.environ["HF_HOME"] = str(SCRIPT_DIR / "HuggingFaceModels")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# [PATH CHANGE] Using 3B model (already on your laptop - same as Hash_Map)
SLM_ID = "Qwen/Qwen2.5-3B-Instruct"

def extract_task_attributes(task_query: str, tokenizer, model) -> list:
    """Uses the SLM to determine the atomic attributes and their normalized priority weights."""
    system_prompt = (
        "You are an ontological physics and tool affordance parser.\n"
        "Your task: The user will provide a physical task. List the ATOMIC physical properties required for the TOOL or INSTRUMENT used, along with a priority weight (float between 0 and 1) for each property.\n\n"
        "RULES:\n"
        "1. FOCUS ONLY ON THE TOOL: Describe the properties of the active instrument doing the work. DO NOT describe the target object.\n"
        "2. FORMAT: Use single snake_case properties.\n"
        "3. WEIGHTS: Assign a priority weight to each attribute such that the sum of all weights equals exactly 1.0.\n"
        "4. OUTPUT: Return ONLY a valid JSON list of dictionaries with keys 'attribute' and 'priority' "
        "(e.g., [{\"attribute\": \"sharp_edge\", \"priority\": 0.7}, {\"attribute\": \"rigid_body\", \"priority\": 0.3}])."
    )
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Task: '{task_query}'"}
    ]
    
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer([text], return_tensors="pt").to(DEVICE)
    
    with torch.no_grad():
        generated_ids = model.generate(**inputs, max_new_tokens=200, do_sample=False)
        
    generated_ids = [out[len(inp):] for inp, out in zip(inputs.input_ids, generated_ids)]
    raw_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
    
    import re, json
    try:
        match = re.search(r"```json\s*(.*?)\s*```", raw_text, re.DOTALL) or re.search(r"(\[.*\])", raw_text, re.DOTALL)
        if match:
            parsed = json.loads(match.group(1).strip())
            if isinstance(parsed, list):
                return parsed
    except Exception:
        pass
    return []

def main():
    print("=" * 60)
    
    # [PATH CHANGE] Get image filename and task from user
    img_filename = input("Enter image filename (e.g., 1.jpg): ").strip()
    task_query = input("Enter task (e.g., 'open a parcel'): ").strip()
    
    # [PATH CHANGE] Construct full input path
    img_path = INPUT_FOLDER / img_filename
    
    print(f"Image Path: {img_path}")
    print(f"Query: {task_query}")
    print("=" * 60)

    if not img_path.exists():
        print("[-] Image not found. Check that the file exists in Input_Images/")
        return

    # [PATH CHANGE] Create task-specific output folder
    task_folder_name = "".join(c for c in task_query if c.isalnum() or c in (' ', '-', '_')).strip().replace(' ', '_')
    OUTPUT_FOLDER = OUTPUT_BASE / task_folder_name
    OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)
    print(f"[*] Output will be saved to: {OUTPUT_FOLDER}")

    # 1. Load SLM & Extract Required Attributes with Weights
    print(f"\n[*] Booting Qwen SLM ({SLM_ID}) on {DEVICE.upper()}...")
    tokenizer = AutoTokenizer.from_pretrained(SLM_ID)
    slm_model = AutoModelForCausalLM.from_pretrained(
        SLM_ID,
        torch_dtype=torch.bfloat16,
        device_map=DEVICE
    ).eval()
    
    required_attrs = extract_task_attributes(task_query, tokenizer, slm_model)
    print(f"\n[!] Raw weighted attributes generated by SLM: {required_attrs}")

    if not required_attrs:
        print("[-] Failed to extract attributes. Exiting.")
        return

    # 2. Graph Traversal: Compute Weighted Scores for Objects
    print("\n[*] Searching Vector Atomic Knowledge Graph with Weighted Scoring...")
    kg = VectorAtomicKnowledgeGraph()
    
    object_scores = {}
    SCORE_THRESHOLD = 0.7  # 70% cumulative priority threshold
    
    for item in required_attrs:
        req_attr = item.get("attribute")
        priority = item.get("priority", 0.0)
        
        matched_node_id = kg._find_or_create_attribute_node(req_attr)
        if matched_node_id and matched_node_id in kg.attributes:
            objs_with_attr = kg.attributes[matched_node_id]["objects"]
            print(f"    ├─ '{req_attr}' (Weight: {priority}) maps to -> {objs_with_attr}")
            
            # Accumulate weight for each object that possesses this attribute
            for obj in objs_with_attr:
                object_scores[obj] = object_scores.get(obj, 0.0) + priority

    print(f"[+] Computed Object Scores: {object_scores}")

    # Filter objects that meet or exceed the score threshold
    common_objects = [obj for obj, score in object_scores.items() if score >= SCORE_THRESHOLD]
    print(f"[+] Graph identified objects meeting >= {int(SCORE_THRESHOLD * 100)}% threshold: {common_objects}")

    if not common_objects:
        print("[-] No known objects met the required score threshold.")
        return

    # 3. Vision Grounding: Scan image for the candidate objects
    print(f"\n[*] Booting Florence-2 on {DEVICE.upper()}...")
    florence_id = "florence-community/Florence-2-base-ft"
    florence_processor = AutoProcessor.from_pretrained(florence_id)
    florence_model = Florence2ForConditionalGeneration.from_pretrained(
        florence_id, torch_dtype=torch.bfloat16 if DEVICE == "cuda" else torch.float32
    ).to(DEVICE).eval()

    image = Image.open(img_path).convert("RGB")
    width, height = image.size
    draw = ImageDraw.Draw(image)
    items_drawn = False

    task_prompt = "<OPEN_VOCABULARY_DETECTION>"
    text_input = task_prompt + ", ".join(common_objects)
    
    inputs = florence_processor(text=text_input, images=image, return_tensors="pt").to(DEVICE)
    with torch.no_grad():
        generated_ids = florence_model.generate(**inputs, max_new_tokens=1024, do_sample=False, num_beams=3)
        
    generated_text = florence_processor.batch_decode(generated_ids, skip_special_tokens=False)[0]
    results = florence_processor.post_process_generation(generated_text, task=task_prompt, image_size=(width, height)).get(task_prompt, {})

    for bbox, label in zip(results.get('bboxes', []), results.get('bboxes_labels', [])):
        x1, y1, x2, y2 = map(int, bbox)
        draw.rectangle([x1, y1, x2, y2], outline="green", width=4)
        draw.text((x1, max(0, y1 - 15)), label.upper(), fill="green")
        items_drawn = True
        print(f"    -> [SUCCESS] Boxed Object: {label.upper()}")

    if items_drawn:
        output_name = f"solved_{img_path.name}"
        output_path = OUTPUT_FOLDER / output_name
        image.save(output_path)
        print(f"\n[+] Task successful! Saved annotated image to '{output_path}'")
    else:
        print("\n[-] The required objects were found in the graph, but Florence-2 did not detect them in this specific image.")

if __name__ == "__main__":
    main()