# import os
# 
# os.environ["HF_HOME"] = "/media/anshdeep-singh/Aditya/HuggingFaceModels"

import torch
import numpy as np
from pathlib import Path
from PIL import Image, ImageDraw
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoProcessor, Florence2ForConditionalGeneration, BitsAndBytesConfig
from atomic_kg_builder import VectorAtomicKnowledgeGraph

# --- CONFIGURATION ---
SCRIPT_DIR = Path(__file__).parent
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SLM_ID = "Qwen/Qwen2.5-3B-Instruct"

def extract_task_attributes(task_query: str, tokenizer, model) -> list:
    """Uses the SLM to determine the atomic attributes required for a task."""
    system_prompt = (
            "You are an ontological physics and tool affordance parser.\n"
            "Your task: The user will provide a physical action or task. You must list the ATOMIC physical properties required for the TOOL or INSTRUMENT used by an agent to successfully perform this action.\n\n"
            "RULES:\n"
            "1. FOCUS ONLY ON THE TOOL: Describe the properties of the active instrument doing the work. DO NOT describe the target object being acted upon (e.g., if the task is 'open a parcel', describe the cutting tool, NOT the box or parcel).\n"
            "2. FORMAT: Use single snake_case properties.\n"
            "3. EXAMPLES of tool properties: sharp_edge, pointed_tip, rigid_body, high_friction, flat_surface, elongated_handle.\n"
            "4. OUTPUT: Return ONLY a valid JSON list of strings and nothing else."
    )
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Task: '{task_query}'"}
    ]
    
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer([text], return_tensors="pt").to(DEVICE)
    
    with torch.no_grad():
        generated_ids = model.generate(**inputs, max_new_tokens=150, do_sample=False)
        
    generated_ids = [out[len(inp):] for inp, out in zip(inputs.input_ids, generated_ids)]
    raw_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
    
    import re, json
    try:
        match = re.search(r"```json\s*(.*?)\s*```", raw_text, re.DOTALL) or re.search(r"(\[.*\])", raw_text, re.DOTALL)
        if match: return json.loads(match.group(1).strip())
    except: pass
    return []

def main():
    print("=" * 60)
    img_path_str = input("Enter image path (e.g., Open_Parcel/1.jpg): ").strip()
    task_query = input("Enter task (e.g., 'cut a piece of paper'): ").strip()
    print("=" * 60)

    img_path = Path(img_path_str)
    if not img_path.exists():
        print("[-] Image not found.")
        return

    # 1. Load SLM & Extract Required Attributes
    print(f"\n[*] Booting Qwen SLM on {DEVICE.upper()}...")
    tokenizer = AutoTokenizer.from_pretrained(SLM_ID)
    # bnb_config = BitsAndBytesConfig(
    #     load_in_8bit=True,
    # )
    slm_model = AutoModelForCausalLM.from_pretrained(
        SLM_ID,
        # quantization_config=bnb_config,
        dtype=torch.bfloat16,
        device_map=DEVICE
    ).eval()
    
    required_attrs = extract_task_attributes(task_query, tokenizer, slm_model)
    
    # NEW PRINT STATEMENT: Explicitly print the SLM's output
    print(f"\n[!] Raw attributes generated by SLM: {required_attrs}")

    if not required_attrs:
        print("[-] Failed to extract attributes. Exiting.")
        return

    # 2. Graph Traversal: Find common objects
    print("\n[*] Searching Vector Atomic Knowledge Graph...")
    kg = VectorAtomicKnowledgeGraph()
    
    # We will find objects that possess ALL required attributes (Intersection)
    candidate_objects_sets = []
    
    for req_attr in required_attrs:
        matched_node_id = kg._find_or_create_attribute_node(req_attr)
        if matched_node_id and matched_node_id in kg.attributes:
            objs_with_attr = set(kg.attributes[matched_node_id]["objects"])
            candidate_objects_sets.append(objs_with_attr)
            print(f"    ├─ '{req_attr}' maps to -> {list(objs_with_attr)}")

    # Intersect all sets to find objects that meet EVERY physical requirement
    if candidate_objects_sets:
        common_objects = list(set.intersection(*candidate_objects_sets))
    else:
        common_objects = []

    print(f"[+] Graph identified common objects: {common_objects}")

    if not common_objects:
        print("[-] No known objects possess all required attributes.")
        return

    # 3. Vision Grounding: Scan image for the candidate objects
    print(f"\n[*] Booting Florence-2 on {DEVICE.upper()}...")
    florence_id = "florence-community/Florence-2-base-ft"
    florence_processor = AutoProcessor.from_pretrained(florence_id)
    florence_model = Florence2ForConditionalGeneration.from_pretrained(
        florence_id, torch_dtype=torch.bfloat16 if DEVICE == "cuda" else torch.float32
    ).to(DEVICE).eval()

    image = Image.open(img_path).convert("RGB")
    width, height = image.size
    draw = ImageDraw.Draw(image)
    items_drawn = False

    task_prompt = "<OPEN_VOCABULARY_DETECTION>"
    # Format the objects as a comma-separated string for Florence-2
    text_input = task_prompt + ", ".join(common_objects)
    
    inputs = florence_processor(text=text_input, images=image, return_tensors="pt").to(DEVICE)
    with torch.no_grad():
        generated_ids = florence_model.generate(**inputs, max_new_tokens=1024, do_sample=False, num_beams=3)
        
    generated_text = florence_processor.batch_decode(generated_ids, skip_special_tokens=False)[0]
    results = florence_processor.post_process_generation(generated_text, task=task_prompt, image_size=(width, height)).get(task_prompt, {})

    for bbox, label in zip(results.get('bboxes', []), results.get('bboxes_labels', [])):
        x1, y1, x2, y2 = map(int, bbox)
        draw.rectangle([x1, y1, x2, y2], outline="green", width=4)
        draw.text((x1, max(0, y1 - 15)), label.upper(), fill="green")
        items_drawn = True
        print(f"    -> [SUCCESS] Boxed Object: {label.upper()}")

    if items_drawn:
        output_name = f"solved_{img_path.name}"
        image.save(output_name)
        print(f"\n[+] Task successful! Saved annotated image to '{output_name}'")
    else:
        print("\n[-] The required objects were found in the graph, but Florence-2 did not detect them in this specific image.")

if __name__ == "__main__":
    main()
