# import os 
# os.environ["HF_HOME"] = "/media/anshdeep-singh/Aditya/HuggingFaceModels"

# import torch
# import numpy as np
# from pathlib import Path
# from PIL import Image, ImageDraw
# from transformers import AutoTokenizer, AutoModelForCausalLM, AutoProcessor, Florence2ForConditionalGeneration, BitsAndBytesConfig
# from atomic_kg_builder import VectorAtomicKnowledgeGraph
# 
# bnb_config = BitsAndBytesConfig(
#     load_in_4bit=True,
#     bnb_4bit_compute_dtype=torch.bfloat16,
#     bnb_4bit_quant_type="nf4"
# )
# 
# # --- CONFIGURATION ---
# SCRIPT_DIR = Path(__file__).parent
# DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
# SLM_ID = "Qwen/Qwen2.5-3B-Instruct"
# 
# def extract_task_attributes(task_query: str, tokenizer, model) -> list:
#     """Uses the SLM to determine the atomic attributes and their normalized priority weights."""
#     system_prompt = (
#         "You are an ontological physics and tool affordance parser.\n"
#         "Your task: The user will provide a physical task. List the ATOMIC physical properties required for the TOOL or INSTRUMENT used, along with a priority weight (float between 0 and 1) for each property.\n\n"
#         "RULES:\n"
#         "1. FOCUS ONLY ON THE TOOL: Describe the properties of the active instrument doing the work. DO NOT describe the target object.\n"
#         "2. FORMAT: Use single snake_case properties.\n"
#         "3. WEIGHTS: Assign a priority weight to each attribute such that the sum of all weights equals exactly 1.0.\n"
#         "4. OUTPUT: Return ONLY a valid JSON list of dictionaries with keys 'attribute' and 'priority' "
#         "(e.g., [{\"attribute\": \"sharp_edge\", \"priority\": 0.7}, {\"attribute\": \"rigid_body\", \"priority\": 0.3}])."
#     )
#     
#     messages = [
#         {"role": "system", "content": system_prompt},
#         {"role": "user", "content": f"Task: '{task_query}'"}
#     ]
#     
#     text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
#     inputs = tokenizer([text], return_tensors="pt").to(DEVICE)
#     
#     with torch.no_grad():
#         generated_ids = model.generate(**inputs, max_new_tokens=200, do_sample=False)
#         
#     generated_ids = [out[len(inp):] for inp, out in zip(inputs.input_ids, generated_ids)]
#     raw_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
#     
#     import re, json
#     try:
#         match = re.search(r"```json\s*(.*?)\s*```", raw_text, re.DOTALL) or re.search(r"(\[.*\])", raw_text, re.DOTALL)
#         if match:
#             parsed = json.loads(match.group(1).strip())
#             if isinstance(parsed, list):
#                 return parsed
#     except Exception:
#         pass
#     return []
# 
# def main():
#     print("=" * 60)
#     # img_path_str = input("Enter image path (e.g., Open_Parcel/1.jpg): ").strip()
#     img_path_str= Path("~/Documents/RM/Input/open_parcel/1.jpg").expanduser()
#     print(f"Image Path: {img_path_str}")
#     # task_query = input("Enter task (e.g., 'cut a piece of paper'): ").strip()
#     task_query= "Cut paper"
#     print(f"Query: {task_query}")
#     print("=" * 60)
# 
#     img_path = Path(img_path_str)
#     if not img_path.exists():
#         print("[-] Image not found.")
#         return
# 
#     # 1. Load SLM & Extract Required Attributes with Weights
#     print(f"\n[*] Booting Qwen SLM on {DEVICE.upper()}...")
#     tokenizer = AutoTokenizer.from_pretrained(SLM_ID)
#     slm_model = AutoModelForCausalLM.from_pretrained(
#         SLM_ID,
#         quantization_config=bnb_config,
#         # torch_dtype=torch.bfloat16,
#         device_map=DEVICE
#     ).eval()
#     
#     required_attrs = extract_task_attributes(task_query, tokenizer, slm_model)
#     print(f"\n[!] Raw weighted attributes generated by SLM: {required_attrs}")
# 
#     if not required_attrs:
#         print("[-] Failed to extract attributes. Exiting.")
#         return
# 
#     # 2. Graph Traversal: Compute Weighted Scores for Objects
#     print("\n[*] Searching Vector Atomic Knowledge Graph with Weighted Scoring...")
#     kg = VectorAtomicKnowledgeGraph()
#     
#     object_scores = {}
#     SCORE_THRESHOLD = 0.9  # 70% cumulative priority threshold
#     
#     for item in required_attrs:
#         req_attr = item.get("attribute")
#         priority = item.get("priority", 0.0)
#         
#         matched_node_id = kg._find_or_create_attribute_node(req_attr)
#         if matched_node_id and matched_node_id in kg.attributes:
#             objs_with_attr = kg.attributes[matched_node_id]["objects"]
#             print(f"    ├─ '{req_attr}' (Weight: {priority}) maps to -> {objs_with_attr}")
#             
#             # Accumulate weight for each object that possesses this attribute
#             for obj in objs_with_attr:
#                 object_scores[obj] = object_scores.get(obj, 0.0) + priority
# 
#     print(f"[+] Computed Object Scores: {object_scores}")
# 
#     # Filter objects that meet or exceed the score threshold
#     common_objects = [obj for obj, score in object_scores.items() if score >= SCORE_THRESHOLD]
#     print(f"[+] Graph identified objects meeting >= {int(SCORE_THRESHOLD * 100)}% threshold: {common_objects}")
# 
#     if not common_objects:
#         print("[-] No known objects met the required score threshold.")
#         return
# 
#     # 3. Vision Grounding: Scan image for the candidate objects
#     print(f"\n[*] Booting Florence-2 on {DEVICE.upper()}...")
#     florence_id = "florence-community/Florence-2-base-ft"
#     florence_processor = AutoProcessor.from_pretrained(florence_id)
#     florence_model = Florence2ForConditionalGeneration.from_pretrained(
#         florence_id, torch_dtype=torch.float32 or (torch.bfloat16 if DEVICE == "cuda" else torch.float32)
#     ).to("cpu").eval()
# 
#     image = Image.open(img_path).convert("RGB")
#     width, height = image.size
#     draw = ImageDraw.Draw(image)
#     items_drawn = False
# 
#     task_prompt = "<OPEN_VOCABULARY_DETECTION>"
#     text_input = task_prompt + ", ".join(common_objects)
#     
#     inputs = florence_processor(text=text_input, images=image, return_tensors="pt").to("cpu")
#     with torch.no_grad():
#         generated_ids = florence_model.generate(**inputs, max_new_tokens=1024, do_sample=False, num_beams=3)
#         
#     generated_text = florence_processor.batch_decode(generated_ids, skip_special_tokens=False)[0]
#     results = florence_processor.post_process_generation(generated_text, task=task_prompt, image_size=(width, height)).get(task_prompt, {})
# 
#     for bbox, label in zip(results.get('bboxes', []), results.get('bboxes_labels', [])):
#         x1, y1, x2, y2 = map(int, bbox)
#         draw.rectangle([x1, y1, x2, y2], outline="green", width=4)
#         draw.text((x1, max(0, y1 - 15)), label.upper(), fill="green")
#         items_drawn = True
#         print(f"    -> [SUCCESS] Boxed Object: {label.upper()}")
# 
#     if items_drawn:
#         output_name = f"solved_{img_path.name}"
#         image.save(output_name)
#         print(f"\n[+] Task successful! Saved annotated image to '{output_name}'")
#     else:
#         print("\n[-] The required objects were found in the graph, but Florence-2 did not detect them in this specific image.")
# 
# if __name__ == "__main__":
#     main()


# ------------------------------------------------- #
# ------------------------------------------------- #
# ------------------------------------------------- #

# import os 
# os.environ["HF_HOME"] = "/media/anshdeep-singh/Aditya/HuggingFaceModels"

import torch
import numpy as np
from pathlib import Path
from PIL import Image, ImageDraw
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoProcessor, Florence2ForConditionalGeneration, BitsAndBytesConfig
from atomic_kg_builder import VectorAtomicKnowledgeGraph

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4"
)

# --- CONFIGURATION ---
SCRIPT_DIR = Path(__file__).parent
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SLM_ID = "Qwen/Qwen2.5-3B-Instruct"

def extract_task_attributes(task_query: str, tokenizer, model) -> list:
    """Uses the SLM to determine the atomic attributes and their normalized priority weights."""
    system_prompt = (
        "You are an ontological physics and tool affordance parser.\n"
        "Your task: The user will provide a physical task. List the ATOMIC physical properties required for the TOOL or INSTRUMENT used, along with a priority weight (float between 0 and 1) for each property.\n\n"
        "RULES:\n"
        "1. FOCUS ONLY ON THE TOOL: Describe the properties of the active instrument doing the work. DO NOT describe the target object.\n"
        "2. FORMAT: Use single snake_case properties.\n"
        "3. WEIGHTS: Assign a priority weight to each attribute such that the sum of all weights equals exactly 1.0.\n"
        "4. OUTPUT: Return ONLY a valid JSON list of dictionaries with keys 'attribute' and 'priority' "
        "(e.g., [{\"attribute\": \"sharp_edge\", \"priority\": 0.7}, {\"attribute\": \"rigid_body\", \"priority\": 0.3}])."
    )
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Task: '{task_query}'"}
    ]
    
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer([text], return_tensors="pt").to(DEVICE)
    
    with torch.no_grad():
        generated_ids = model.generate(**inputs, max_new_tokens=200, do_sample=False)
        
    generated_ids = [out[len(inp):] for inp, out in zip(inputs.input_ids, generated_ids)]
    raw_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
    
    import re, json
    try:
        match = re.search(r"```json\s*(.*?)\s*```", raw_text, re.DOTALL) or re.search(r"(\[.*\])", raw_text, re.DOTALL)
        if match:
            parsed = json.loads(match.group(1).strip())
            if isinstance(parsed, list):
                return parsed
    except Exception:
        pass
    return []

def filter_top_objects(objects_list: list, tokenizer, model) -> list:
    """Uses the SLM to select the top 3 objects and strip appearance adjectives."""
    system_prompt = (
        "You are a semantic filter. The user will provide a list of objects.\n"
        "Your task:\n"
        "1. Select a maximum of the top 3 most fundamental and useful objects from the list.\n"
        "2. Strip away any appearance-related adjectives (e.g., colors, materials like 'red', 'wooden', 'shiny'). For example, 'red scissors' becomes 'scissors', and 'wooden handle' becomes 'handle'.\n"
        "3. Return ONLY a valid JSON list of strings containing exactly the cleaned object names.\n"
        "Example output: [\"scissors\", \"knife\", \"blade\"]"
    )
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Objects: {objects_list}"}
    ]
    
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer([text], return_tensors="pt").to(DEVICE)
    
    with torch.no_grad():
        generated_ids = model.generate(**inputs, max_new_tokens=100, do_sample=False)
        
    generated_ids = [out[len(inp):] for inp, out in zip(inputs.input_ids, generated_ids)]
    raw_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
    
    import re, json
    try:
        match = re.search(r"```json\s*(.*?)\s*```", raw_text, re.DOTALL) or re.search(r"(\[.*\])", raw_text, re.DOTALL)
        if match:
            parsed = json.loads(match.group(1).strip())
            if isinstance(parsed, list):
                return parsed[:3]
    except Exception as e:
        print(f"[-] SLM parsing failed during filtering: {e}")
        
    # Fallback to original top 3 if parsing fails to prevent pipeline crash
    return objects_list[:3]

def main():
    print("=" * 60)
    # img_path_str = input("Enter image path (e.g., Open_Parcel/1.jpg): ").strip()
    img_path_str= Path("~/Documents/RM/Input/open_parcel/1.jpg").expanduser()
    print(f"Image Path: {img_path_str}")
    # task_query = input("Enter task (e.g., 'cut a piece of paper'): ").strip()
    task_query= "Cut paper"
    print(f"Query: {task_query}")
    print("=" * 60)

    img_path = Path(img_path_str)
    if not img_path.exists():
        print("[-] Image not found.")
        return

    # 1. Load SLM & Extract Required Attributes with Weights
    print(f"\n[*] Booting Qwen SLM on {DEVICE.upper()}...")
    tokenizer = AutoTokenizer.from_pretrained(SLM_ID)
    slm_model = AutoModelForCausalLM.from_pretrained(
        SLM_ID,
        quantization_config=bnb_config,
        # torch_dtype=torch.bfloat16,
        device_map=DEVICE
    ).eval()
    
    required_attrs = extract_task_attributes(task_query, tokenizer, slm_model)
    print(f"\n[!] Raw weighted attributes generated by SLM: {required_attrs}")

    if not required_attrs:
        print("[-] Failed to extract attributes. Exiting.")
        return

    # 2. Graph Traversal: Compute Weighted Scores for Objects
    print("\n[*] Searching Vector Atomic Knowledge Graph with Weighted Scoring...")
    kg = VectorAtomicKnowledgeGraph()
    
    object_scores = {}
    SCORE_THRESHOLD = 0.9  # 70% cumulative priority threshold
    
    for item in required_attrs:
        req_attr = item.get("attribute")
        priority = item.get("priority", 0.0)
        
        matched_node_id = kg._find_or_create_attribute_node(req_attr)
        if matched_node_id and matched_node_id in kg.attributes:
            objs_with_attr = kg.attributes[matched_node_id]["objects"]
            print(f"    ├─ '{req_attr}' (Weight: {priority}) maps to -> {objs_with_attr}")
            
            # Accumulate weight for each object that possesses this attribute
            for obj in objs_with_attr:
                object_scores[obj] = object_scores.get(obj, 0.0) + priority

    print(f"[+] Computed Object Scores: {object_scores}")

    # Filter objects that meet or exceed the score threshold
    common_objects = [obj for obj, score in object_scores.items() if score >= SCORE_THRESHOLD]
    print(f"[+] Graph identified objects meeting >= {int(SCORE_THRESHOLD * 100)}% threshold: {common_objects}")

    if not common_objects:
        print("[-] No known objects met the required score threshold.")
        return

    # 2.5 Secondary SLM Pass: Filter and Clean
    print("\n[*] Passing candidate objects back to SLM for top 3 selection and adjective stripping...")
    refined_objects = filter_top_objects(common_objects, tokenizer, slm_model)
    print(f"[+] Refined Top 3 Objects: {refined_objects}")

    if not refined_objects:
        print("[-] Failed to refine objects. Exiting.")
        return

    # 3. Vision Grounding: Scan image for the candidate objects
    print(f"\n[*] Booting Florence-2 on {DEVICE.upper()}...")
    florence_id = "florence-community/Florence-2-base-ft"
    florence_processor = AutoProcessor.from_pretrained(florence_id)
    florence_model = Florence2ForConditionalGeneration.from_pretrained(
        florence_id, torch_dtype=torch.float32 or (torch.bfloat16 if DEVICE == "cuda" else torch.float32)
    ).to("cpu").eval()

    image = Image.open(img_path).convert("RGB")
    width, height = image.size
    draw = ImageDraw.Draw(image)
    items_drawn = False

    task_prompt = "<OPEN_VOCABULARY_DETECTION>"
    # Pass the refined objects instead of common_objects
    text_input = task_prompt + ", ".join(refined_objects)
    
    inputs = florence_processor(text=text_input, images=image, return_tensors="pt").to("cpu")
    with torch.no_grad():
        generated_ids = florence_model.generate(**inputs, max_new_tokens=1024, do_sample=False, num_beams=3)
        
    generated_text = florence_processor.batch_decode(generated_ids, skip_special_tokens=False)[0]
    results = florence_processor.post_process_generation(generated_text, task=task_prompt, image_size=(width, height)).get(task_prompt, {})

    for bbox, label in zip(results.get('bboxes', []), results.get('bboxes_labels', [])):
        x1, y1, x2, y2 = map(int, bbox)
        draw.rectangle([x1, y1, x2, y2], outline="green", width=4)
        draw.text((x1, max(0, y1 - 15)), label.upper(), fill="green")
        items_drawn = True
        print(f"    -> [SUCCESS] Boxed Object: {label.upper()}")

    if items_drawn:
        output_name = f"solved_{img_path.name}"
        image.save(output_name)
        print(f"\n[+] Task successful! Saved annotated image to '{output_name}'")
    else:
        print("\n[-] The required objects were found in the graph, but Florence-2 did not detect them in this specific image.")

if __name__ == "__main__":
    main()
